### ISSUE TITLE
No diagrams overlap selections. 

### ISSUE THREAD

**Issue by tooh** [jvantuyl/sublime_diagram_plugin#38] opened 2015-11-01 09:47 UTC
Followed the instructions but no diagram is produced.

Environment OSX El Capitan

Steps to reproduce
1. select plantuml text in editor
2. press CMD-M

I get the error message:

```
No diagrams overlap selections
```

Is triggered with this code

```
class DisplayDiagrams(TextCommand):
    def run(self, edit):
        print("Processing diagrams in %r..." % self.view)
        if not process(self.view):
            error_message("No diagrams overlap selections.\n\n" \
                "Nothing to process.")
```

**Comment by rbaylis91** [comment] 2016-01-09 06:18
Seeing this as well...

**Comment by ivhong** [comment] 2016-06-12 11:01
I have encountered the same problem? How did you solve it?

**Comment by ivhong** [comment] 2016-06-12 11:05
diagram.__init__.py
Line:93 , 
Code: for block in processor.extract_blocks(view):


I found this loop can't go in.

**Comment by ivhong** [comment] 2016-06-12 11:14
@startuml
@enduml

**Comment by jvantuyl** [comment] 2016-06-12 11:23
What do you mean by "select plantuml text in editor"?

Are you dragging a selection over it, just focusing the tab, or placing a cursor inside of it?

It *should* work if you drag a selection.  Anything else doesn't work unless you have @startuml / @enduml around it.

**Comment by aubryfr** [comment] 2016-07-13 15:52
If anybody else encounters this, try to restart Sublime Text. It solved the problem for me, it might as easy as that for you too !
I had the problem right after installing the package, but a restart made it work just fine.

@jvantuyl, for your information :
- Sublime Text 3 (3114), Ubuntu 16.04 LTS
- installation scenario : installed the package / tried the plugin (failed because plantuml was missing) / installed plantuml / tried the plugin (failed as described above) / restarted ST => worked

And while I'm here, thanks for this very useful plugin ! :+1:

**Comment by jvantuyl** [comment] 2018-01-09 14:44
Closing this. Can’t reproduce, don’t think it applies any more.

**Closed by jvantuyl** 2018-01-09 14:44 UTC
